#!/usr/bin/env python

# Copyright (c) 2009-2014 by Farsight Security, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from subprocess import Popen, PIPE
import os
import sys

p = Popen('pkg-config --cflags-only-I libwdns', shell=True, stdout=PIPE)
if p.wait() != 0:
    sys.stderr.write('pkg-config failed\n')
    sys.exit(1)
out = p.stdout.read().strip().decode('utf-8')
if out:
    header_dir = out.partition('-I')[2]
    header_fname = header_dir + '/wdns.h'
else:
    header_fname = '/usr/include/wdns.h'

if not os.path.isfile(header_fname):
    sys.stderr.write('unable to open %s\n' % header_fname)
    sys.exit(1)

w = open('wdns_constants.py', 'w')

for line in open(header_fname):
    if 'WDNS_TYPE_' in line:
        rrtype = line.split()[1].split('_', 2)[2]
        rrtype_val = line.split()[-1]
        w.write('TYPE_%s = %s\n' % (rrtype, rrtype_val))
    elif 'WDNS_CLASS_' in line:
        rrclass = line.split()[1].split('_', 2)[2]
        rrclass_val = line.split()[-1]
        w.write('CLASS_%s = %s\n' % (rrclass, rrclass_val))
    elif 'WDNS_MSG_SEC_' in line:
        sec = line.split()[1].split('_', 3)[3]
        sec_val = line.split()[-1]
        w.write('SEC_%s = %s\n' % (sec, sec_val))
    elif 'WDNS_OP_' in line:
        op = line.split()[1].split('_', 2)[2]
        op_val = line.split()[-1]
        w.write('OP_%s = %s\n' % (op, op_val))
    elif 'WDNS_R_' in line:
        r = line.split()[1].split('_', 2)[2]
        r_val = line.split()[-1]
        w.write('R_%s = %s\n' % (r, r_val))

w.write('TYPES = {\n')

for line in open(header_fname):
    if 'WDNS_TYPE_' in line:
        rrtype = line.split()[1].split('_', 2)[2]
        rrtype_val = line.split()[-1]
        w.write("'%s': %s,\n" % (rrtype, rrtype_val))

w.write('}\n')

w.close()
